name: Print Hello World

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Hello:
    runs-on: ubuntu-22.04
    steps:
      - name: Hello World!
        run: echo "Hello World"
